# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_uforemote_wrappers", use_symbols = TRUE, package_name = "uforemote")

#' @docType package
#' @usage NULL
#' @useDynLib uforemote, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Start listening to remote execution requests
#' @export
listen <- function(port) invisible(.Call(wrap__listen, port))

#' Execute 
#' @export
execute <- function(code) .Call(wrap__execute, code)

